### ISSUE TITLE
rename this repo, to emphasize docs/sphinx

### ISSUE THREAD

**Issue by velle** [qgis/pyqgis-api-docs-builder#125]
pyqgis normally refers to the Python binding for QGIS. 

Yet the https://github.com/qgis/pyqgis repo is concerned with only one technical detail of the entire thing, ie autogenerating html docs of the pyqgis API, using the tool Sphinx. 

I'm sure almost every pyqgis user must have visited this github project in vain at some time :)

Why does it have this name? Was there a time, where pyqgis (the API) actually resided here? 

In any case, I believe it would be common sense to rename the repo into "pyqgis-sphinx" or similar.  

Renaming it to "pyqgis-docs" would be an improvement, but with that name users still might go there with issues concerned with the documentation itself (typos, incorrect information, etc.). 

Sincerely

**Comment by jfbourdon** [comment]
> I'm sure almost every pyqgis user must have visited this github project in vain at some time :)

I concur, I have once been this user and it took me a while to understand that it wasn't the place at all if I wanted to edit some part of the doc. In addition to (or in lieu of) a rename of the repo, a note could be added to the main README.md saying explicitly that any change to the documentation itseft has be to made elsewhere.

Also, in order to avoid getting lost pyqgis users here, I think that adding a button saying "Edit on GitHub" at the top of each page of https://qgis.org/pyqgis/ linking to right file on the main QGIS repo would help a lot.

**Comment by DelazJ** [comment]
> Also, in order to avoid getting lost pyqgis users here, I think that adding a button saying "Edit on GitHub" at the top of each page of https://qgis.org/pyqgis/ linking to right file on the main QGIS repo would help a lot.

See #37 for some context on this request
> a note could be added to the main README.md saying explicitly that any change to the documentation itseft has be to made elsewhere

Pull request welcome 😉 
And this information could also be placed in the (to be renamed) "[bug reporting _and fixes_](https://qgis.org/pyqgis/master/#bug-reporting)" section of the PyQGIS website main page.

**Comment by 3nids** [comment]
related #144

**Comment by 3nids** [comment]
@DelazJ what about renaming it to `pyqgis-api-docs-builder` ?
if we do so, is there anything to be done to adapt the redirection from qgis.org/pyqgis ?

**Comment by DelazJ** [comment]
>@DelazJ what about renaming it to pyqgis-api-docs-builder ?

Sounds good to me. @velle @jfbourdon Does this look more meaningful to you?
> if we do so, is there anything to be done to adapt the redirection from qgis.org/pyqgis ?

"redirection"? I'm not sure I understand; do you suggest to rename also https://qgis.org/pyqgis? Is it worth it? If so there are indeed many places we would also need to update the links.
Otherwise, if we just rename the repo, the place that comes to my mind for url adjustment is the [issue report link](https://github.com/qgis/pyqgis/blob/master/_templates/versions.html#L55) in the bottom left menu. I'm not sure this repository name is "used" anywhere else.

**Comment by 3nids** [comment]
@DelazJ no, I'm just saying that qgis.org/pyqgis point to the Github pages. That probably needs to be adapted.

**Comment by velle** [comment]
> @DelazJ what about renaming it to pyqgis-api-docs-builder ?

That seems descriptive and meaningful :)

**Comment by jfbourdon** [comment]
I also agree that *pyqgis-api-docs-builder* is pretty meaningful. Thanks for all the related tasks to this.

**Comment by DelazJ** [comment]
ouch...! @3nids The renaming broke the online docs. So yes, there is some redirection settings to adjust, either in the repo settings or on our server...

**Comment by Xpirix** [comment]
Hello everyone, 

I wonder if the repo is serving the GitHub page. I tried to browse https://qgis.github.io/pyqgis-api-docs-builder/master/ but it redirects to https://qgis.org/master/. But I think it should be the other way around. We've set the proxy pass rule for https://qgis.org/pyqgis/ to https://qgis.github.io/pyqgis/ but it could be changed to https://qgis.github.io/pyqgis-api-docs-builder/ to proxy pass the new GH page.

Regards,

**Comment by 3nids** [comment]
@Xpirix thanks for the pointer. I think I messed up with the pages config by setting a custom domain there. I removed this and now https://qgis.github.io/pyqgis-api-docs-builder/master/ is actually working.

But https://qgis.org/pyqgis/master/ is still not working because I believe it's still pointing to the old https://qgis.github.io/pyqgis/master/

So I believe this is something to fix on qgis.org server. 
@DelazJ do you have access to this? or @mbernasocchi may I ask your help here?

**Comment by Xpirix** [comment]
Hi @3nids, It seems that the Python API docs returns an error 404. Does the GH page still work?

**Comment by 3nids** [comment]
@Xpirix thanks for the pointer, hopefully solved here https://github.com/qgis/pyqgis-api-docs-builder/commit/fbdfd9688f3fe0298f155d839384f15e39f28585#diff-4fdc48ab490b670c90974725b8e3d399b24c03d6d09563acf8ea87d4113930fbL64

**Comment by Xpirix** [comment]
Hi @3nids , thanks for the fix. https://qgis.github.io/pyqgis-api-docs-builder is now working. However, https://qgis.github.io/pyqgis-api-docs-builder/master redirects to qgis.org/master and https://qgis.github.io/pyqgis-api-docs-builder/3.34 returns a 404.

Do you think that the redirection from qgis.org needs some tweaks? Thanks.

**Comment by 3nids** [comment]
I'm still on this. The main page points to 3.34 and it should not. sorry for the delay, it takes a lot of time to build at each try.

**Comment by 3nids** [comment]
I have good hopes that the last one will be the right one!!!
