### ISSUE TITLE
Docs for members

### ISSUE THREAD

**Issue by nyalldawson** [qgis/pyqgis-api-docs-builder#27]
Looking into why https://qgis.org/pyqgis/3.4/core/Raster/QgsRasterHistogram.html has such poor docs, it's because the member variable documentation isn't transferred to sip docstrings.

This isn't currently supported by sip, but I think it *should* be possible. See https://stackoverflow.com/a/40488936/1861260

**Comment by 3nids** [comment]
I think that SIP will return an error if you try to document a member, have you tested?
It might be possible to bring that to PyQt list and to see it fixed, but I guess this is not a trivial fix.

But anyway, this kind of class is not very common in the API. I have no strong opinion, but it seems we should try to stay coherent and offer setters/getters rather than making the members public. But it's maybe off-topic.

**Comment by nyalldawson** [comment]
Yes, sip errors. I guess there's a lot of parts involved here -- sipify, pyqt, sphinx,...  I'd be inclined to agree with you that's it's too much effort, but then.. I don't like missing nice stuff :p

**Comment by 3nids** [comment]
sipify and sphinx are the easy parts ;) I'll be happy to tackle them if you do the SIP part.
Or just refactor the class with setters and getters (a V2 and implicit conversion)?

**Comment by nyalldawson** [comment]
@3nids do you have a way to locally test the doc generation?

**Comment by 3nids** [comment]
yes I do. There is also a build on any pull request on this repo, and the generated docs are accessible here https://qgis.org/pyqgis/master_temp/

**Comment by 3nids** [comment]
I asked for enum on the list 
https://www.riverbankcomputing.com/pipermail/pyqt/2019-March/041423.html

Another easier approach might be to create extra files with sipify and integrate them in sphinx.
