### ISSUE TITLE
Add a link to the source code page to ease fixes

### ISSUE THREAD

**Issue by DelazJ** [qgis/pyqgis-api-docs-builder#37]
When you are browsing https://qgis.org/pyqgis/master and you find an issue, it might be really really convenient if there was a "fix me" link in the footer that would bring you to the class page (.h?) in qgis/QGIS repository. That would make contribution easier to proceed (we have this in qgis/QGIS-Documentation and it greatly saves time, avoiding waste of time with search in the repository)

**Comment by 3nids** [comment]
there is a nice extension for this: https://www.sphinx-doc.org/en/master/usage/extensions/linkcode.html#confval-linkcode_resolve

but:
1) we currently don't have a map class -> header file (some in subfolders, some in different header name
2) we would link to editing the header file: any PR would fail because of sipify tests

2) is not that big a deal
To handle 1), we could create this map with sipify, but that's a bit of work. Do you think it's worth it?

**Comment by DelazJ** [comment]
Sorry for the late reply @3nids
> Do you think it's worth it?

I can't tell. It may depend on how many potential fixers we have/want/can expect. I know that I have occasions I could have fixed a formatting rendering and that I postponed (_read "did not do"_) that because no time to browse the code and find the proper class (github search tool is not always the best). And I'm a bit aware of QGIS code structure so it may be less obvious for occasional contributors.
Sorry to not be of great help.

**Comment by jfbourdon** [comment]
>Do you think it's worth it?

To answer 4 years later, I would say that with a "fix me" link, I would have made some edits as it removes a big barrier (finding which file has to be edited).

Does having this kind of button would result in having loads of PyQGIS users making edits? Probably not, but as the user base of QGIS is always growing there will be more and more users potentially willing to take time to do so once in a while.

**Comment by DelazJ** [comment]
Fixed. Thanks @3nids
